[package]
name = "aoide-client"
version = "0.0.0"
edition = "2018"

[dependencies]
anyhow = "*"
env_logger = "*"
log = "*"
reqwest = { version = "*", default-features = false, features = ["rustls-tls"] }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = "*"
url = { version = "*", default-features = false, features = ["serde"] }

# Parent workspace
aoide-core = "*"
aoide-core-serde = "*"
