[package]
name = "aoide-websrv-api"
version = "0.8.0"
license-file = "LICENSE.md"
description = "A web service for managing and exploring music collections"
keywords = ["music", "collection"]
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.56"
log = "0.4.14"
serde = "1.0.136"
thiserror = "1.0.30"
tokio = "1.17.0"
warp = { version = "0.3.2", default-features = false }

# Workspace dependencies
aoide-backend-webapi-json = "*"
aoide-repo = "*"
aoide-storage-sqlite = "*"
aoide-usecases-sqlite = { version = "*", features = ["with-tokio-runtime"] }
