[package]
name = "aoide-usecases"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.56"
bitflags = "1.3.2"
blake3 = "1.3.1"
log = "0.4.16"
semval = "0.2.0"
thiserror = "1.0.30"
url = "2.2.2"
walkdir = "2.3.2"

# Workspace dependencies
aoide-core = { version = "*", features = ["with-std-file", "with-std-system-time"] }
aoide-core-api = "*"
aoide-media = "*"
aoide-repo = "*"

[features]
default = []
