# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-usecases"
description = "aoide - Storage-agnostic use case implementations for the backend"
repository = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = "1.0.71"
bitflags = "2.3.1"
log = "0.4.18"
thiserror = "1.0.40"

# Workspace dependencies
aoide-core = { version = "=0.8.0", path = "../core" }
aoide-core-api = { version = "=0.8.0", path = "../core-api" }
aoide-repo = { version = "=0.8.0", path = "../repo" }

# Workspace dependencies (optional): media
aoide-media-file = { version = "=0.8.0", path = "../media-file", optional = true }
blake3 = { version = "1.3.3", optional = true }
url = { version = "2.3.1", optional = true }
walkdir = { version = "2.3.3", optional = true }

# Feature to enable JavaScript bindings on wasm32-unknown-unknown
[features]
default = []
media-file = ["dep:aoide-media-file", "dep:blake3", "dep:url", "dep:walkdir"]
js = ["aoide-core/js", "aoide-core-api/js", "aoide-repo/js"]
