# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-usecases"
description = "aoide - Storage-agnostic use case implementations for the backend"
publish = false
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.86"
bitflags = "2.6.0"
digest = "0.10.7"
log = "0.4.22"
static_assertions = "1.1.0"
thiserror = "1.0.63"

# Workspace dependencies
aoide-core.workspace = true
aoide-core-api.workspace = true
aoide-repo.workspace = true

# Workspace dependencies (optional): media-file
aoide-media-file = { workspace = true, optional = true }
blake3 = { version = "1.5.3", optional = true }
url = { version = "2.5.2", optional = true }
walkdir = { version = "2.5.0", optional = true }

# Feature to enable JavaScript bindings on wasm32-unknown-unknown
[features]
default = []
media-file = ["dep:aoide-media-file", "dep:blake3", "dep:url", "dep:walkdir"]
