[package]
name = "aoide-usecases"
description = "aoide - Storage-agnostic use case implementations"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bitflags = "1.3.2"
blake3 = "1.3.1"
log = "0.4.17"
semval = "0.3.0"
thiserror = "1.0.31"
url = "2.2.2"
walkdir = "2.3.2"

# Workspace dependencies
aoide-core = { version = "=0.8.0", default-features = false }
aoide-core-api = "=0.8.0"
aoide-media = "=0.8.0"
aoide-repo = "=0.8.0"

[features]
default = ["std"]
std = ["aoide-core/std"]
