# SPDX-FileCopyrightText: Copyright (C) 2018-2025 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-usecases"
description = "aoide - Storage-agnostic use case implementations for the backend"
publish = false
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
digest.workspace = true
log.workspace = true
nonicle.workspace = true
same-file = "1.0.6"
semval.workspace = true
static_assertions.workspace = true
thiserror.workspace = true

# Workspace dependencies
aoide-core.workspace = true
aoide-core-api.workspace = true
aoide-repo.workspace = true

# Workspace dependencies (optional): media-file
aoide-media-file = { workspace = true, optional = true }
blake3 = { version = "1.5.5", optional = true }
url = { workspace = true, optional = true }
walkdir = { version = "2.5.0", optional = true }

# Feature to enable JavaScript bindings on wasm32-unknown-unknown
[features]
default = []
expensive-debug-assertions = []
media-file = ["dep:aoide-media-file", "dep:blake3", "dep:url", "dep:walkdir"]
