[package]
name = "aoide-usecases"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "*"
bitflags = "*"
blake3 = "*"
digest = "*"
log = "*"
semval = "*"
thiserror = "*"
url = "*"
walkdir = "*"

# Workspace dependencies
aoide-core = "*"
aoide-core-api = "*"
aoide-media = "*"
aoide-repo = "*"

[features]
default = []
