# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-usecases"
description = "aoide - Storage-agnostic use case implementations for the backend"
publish = false
version = "0.0.0"
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = "1.0.82"
bitflags = "2.5.0"
digest = "0.10.7"
log = "0.4.21"
static_assertions = "1.1.0"
thiserror = "1.0.59"

# Workspace dependencies
aoide-core = { version = "=0.0.0", path = "../core" }
aoide-core-api = { version = "=0.0.0", path = "../core-api" }
aoide-repo = { version = "=0.0.0", path = "../repo" }

# Workspace dependencies (optional): media-file
aoide-media-file = { version = "=0.0.0", path = "../media-file", optional = true }
blake3 = { version = "1.5.1", optional = true }
url = { version = "2.5.0", optional = true }
walkdir = { version = "2.5.0", optional = true }

# Feature to enable JavaScript bindings on wasm32-unknown-unknown
[features]
default = []
media-file = ["dep:aoide-media-file", "dep:blake3", "dep:url", "dep:walkdir"]
