[package]
name = "aoide-usecases"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1"
bitflags = "1.3"
blake3 = "1.3"
log = "0.4"
semval = "0.2"
thiserror = "1"
url = "2.2"
walkdir = "2.3"

# Workspace dependencies
aoide-core = "*"
aoide-core-api = "*"
aoide-media = "*"
aoide-repo = "*"

[features]
default = []
