[package]
name = "aoide-usecases"
description = "aoide - Storage-agnostic use case implementations for the backend"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bitflags = "1.3.2"
log = "0.4.17"
semval = "0.3.0"
thiserror = "1.0.31"

# Workspace dependencies
aoide-core = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-repo = "=0.8.0"

# Workspace dependencies (optional): media
aoide-media = { version = "=0.8.0", optional = true }
blake3 = { version = "1.3.1", optional = true }
url = { version = "2.2.2", optional = true }
walkdir = { version = "2.3.2", optional = true }

# Feature to enable JavaScript bindings on wasm32-unknown-unknown
[features]
default = []
# The features "media" and "js" are mutually exclusive
media = ["aoide-media", "blake3", "url", "walkdir"]
js = ["aoide-core/js", "aoide-core-api/js", "aoide-repo/js"]
