# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-usecases"
description = "aoide - Storage-agnostic use case implementations for the backend"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.69"
bitflags = "1.3.2"
log = "0.4.17"
thiserror = "1.0.39"

# Workspace dependencies
aoide-core = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-repo = "=0.8.0"

# Workspace dependencies (optional): media
aoide-media = { version = "=0.8.0", optional = true }
blake3 = { version = "1.3.3", optional = true }
url = { version = "2.3.1", optional = true }
walkdir = { version = "2.3.2", optional = true }

# Feature to enable JavaScript bindings on wasm32-unknown-unknown
[features]
default = []
media = ["aoide-media", "blake3", "url", "walkdir"]
js = ["aoide-core/js", "aoide-core-api/js", "aoide-repo/js"]
