[package]
name = "aoide-usecases-sqlite-json"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1"
diesel = { version = "1.4.8", default-features = false, features = ["sqlite"] }
log = "0.4"
serde = { version = "1", default-features = false }
thiserror = "1"
url = "2.2"

# tracing
tracing = { version = "0.1", features = ["log"] }
uuid = { version = "0.8", features = ["v4"] }

# JSON Schema (optional)
schemars = { version = "0.8", optional = true }

# Workspace dependencies
aoide-core = "*"
aoide-core-api = "*"
aoide-core-json = "*"
aoide-core-api-json = { version = "*", features = ["backend"] }
aoide-media = "*"
aoide-repo = "*"
aoide-usecases = "*"
aoide-usecases-sqlite = "*"

[features]
default = []
with-schemars = [
    "schemars",
    "aoide-core-api-json/with-schemars",
    "aoide-core-json/with-schemars",
]
