# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

# Configuration file for https://stoplight.io/open-source/spectral

extends: [[spectral:oas, all]]
rules:
  contact-properties: false
  tag-description: false
  openapi-tags-alphabetical: false
  operation-operationId: false
  operation-singular-tag: true
