# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: CC0-1.0

[graph]
all-features = true

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
# TODO: Remove this exception when it is no longer needed.
ignore = [{ id = "RUSTSEC-2024-0384", reason = "needed by tantivy v0.22.0" }]

[licenses]
allow = [
  "AGPL-3.0",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Unlicense",
  "zlib-acknowledgement",
  "Zlib",
]

[bans]
multiple-versions = "allow"
highlight = "all"
