image: docker:19

stages:
  - pre-build
  - build

services:
  - docker:dind

variables:
  GIT_DEPTH: 1
  DOCKER_DRIVER: overlay2
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/build
  COMMIT_IMAGE: $CI_REGISTRY_IMAGE/commit

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:image:
  stage: pre-build
  script:
    - docker pull $BUILD_IMAGE:$CI_COMMIT_BEFORE_SHA || true
    - docker pull $BUILD_IMAGE:$CI_COMMIT_SHA || true
    - docker pull $BUILD_IMAGE:latest || true
    - docker build --target build --cache-from $BUILD_IMAGE:$CI_COMMIT_BEFORE_SHA --cache-from $BUILD_IMAGE:$CI_COMMIT_SHA --cache-from $BUILD_IMAGE:latest --tag $BUILD_IMAGE:$CI_COMMIT_SHA --tag $BUILD_IMAGE:latest .
    - docker push $BUILD_IMAGE:$CI_COMMIT_SHA
    - docker push $BUILD_IMAGE:latest

build:commit:
  stage: build
  script:
    - docker pull $BUILD_IMAGE:$CI_COMMIT_SHA || true
    - docker pull $BUILD_IMAGE:$latest || true
    - docker build --cache-from $BUILD_IMAGE:$CI_COMMIT_SHA --cache-from $BUILD_IMAGE:latest --tag $COMMIT_IMAGE:$CI_COMMIT_SHA .
    - docker push $COMMIT_IMAGE:$CI_COMMIT_SHA
  except:
    - tags

build:tag:
  stage: build
  script:
    - docker pull $BUILD_IMAGE:$CI_COMMIT_SHA || true
    - docker pull $BUILD_IMAGE:$latest || true
    - docker build --cache-from $BUILD_IMAGE:$CI_COMMIT_SHA --cache-from $BUILD_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
