# Only add deviations from the default settings!

# Consistently use a single edition for all workspace crates, should match Cargo.toml
edition = "2021"

use_field_init_shorthand = true
use_try_shorthand = true

# TODO: Enable when available on the stable channel
#format_strings = true
#imports_granularity = "Crate"
#group_imports = "StdExternalCrate"

# Treat code in doc comments as regular code
# TODO: Enable when available on the stable channel and still not the default!
#format_code_in_doc_comments = true

# Comments should be treated like any other code. Reword your comments or add
# manual breaks if needed.
# TODO: Enable when available on the stable channel and still not the default!
#wrap_comments = true
