[package]
name = "aoide"
version = "0.8.0"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
description = "A web service for managing and exploring music collections"
keywords = ["music", "library", "management"]
publish = false
edition = "2018"

[workspace]
members = [
  "./",
  "core",
  "core-serde",
  "media",
  "repo",
  "repo-sqlite",
]

[patch.crates-io]
aoide-core = { path = "core" }
aoide-core-serde = { path = "core-serde" }
aoide-media = { path = "media" }
aoide-repo = { path = "repo" }
aoide-repo-sqlite = { path = "repo-sqlite" }

[dependencies]
aoide-core = "*"
aoide-core-serde = "*"
aoide-media = "*"
aoide-repo = "*"
aoide-repo-sqlite = "*"
chrono = { version = "*", default-features = false }
diesel = { version = "*", default-features = false, features = ["r2d2", "sqlite"] }
diesel_migrations =  { version = "*", default-features = false, features = ["sqlite"] }
dotenv = "*"
env_logger = "*"
futures = "*"
anyhow = "*"
log = "*"
r2d2 = "*"
semval = { version = ">= 0.1.5" }
serde = "*"
serde_json = "*"
thiserror = "*"
tokio = { version = "*", default-features = false, features = ["macros", "rt-threaded"] }
url = { version = "*", features = ["serde"] }
warp = { version = "*", default-features = false }

[features]
default = []

[dev-dependencies]
serde_urlencoded = "*"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
