[package]
name = "aoide"
version = "0.5.1"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
description = "A web service for managing and exploring music collections"
keywords = ["music", "library", "management"]
publish = false
edition = "2018"

[workspace]
members = [
  "./",
  "core",
  "core-serde",
  "repo",
  "repo-sqlite",
]

[patch.crates-io]
aoide-core = { path = "core" }
aoide-core-serde = { path = "core-serde" }
aoide-repo = { path = "repo" }
aoide-repo-sqlite = { path = "repo-sqlite" }

[dependencies]
aoide-core = "*"
aoide-core-serde = "*"
aoide-repo = "*"
aoide-repo-sqlite = "*"
chrono = { version = "*", default-features = false }
clap = "*"
diesel = { version = "*", default-features = false, features = ["r2d2", "sqlite"] }
diesel_migrations =  { version = "*", default-features = false, features = ["sqlite"] }
env_logger = "*"
failure = { version = "*", default-features = false, features = ["std"] }
futures = "0.1"
log = "*"
semval = "*"
serde = "*"
serde_json = "*"
tokio = { version = "0.1", default-features = false }
warp = { version = "0.1", default-features = false }

[dev-dependencies]
serde_urlencoded = "*"

[profile.release]
lto = true
codegen-units = 1
