[package]
name = "aoide"
version = "0.0.1"
authors = [ "Uwe Klotz <uwe.klotz@gmail>" ]
description = "Backend services for curating and enjoying your music"
publish = false

[workspace]
members = [
  "./",
  "aoide-core",
  "aoide-storage",
]

[patch.crates-io]
aoide-core = { path = "aoide-core" }
aoide-storage = { path = "aoide-storage" }

[dependencies]
aoide-core = { version = "*", path = "aoide-core" }
aoide-storage = { version = "*", path = "aoide-storage" }

actix = { git = "https://github.com/actix/actix" }
actix-web = { git = "https://github.com/actix/actix-web" }
clap = "*"
diesel = { version = "*", features = ["r2d2", "sqlite"] }
diesel_migrations =  { version = "*", features = ["sqlite"] }
env_logger = "*"
failure = { version = "*", features = ["std"] }
# futures 0.1.x: Version pinned for Actix
futures = "0.1.*"
hyper = "*"
libsqlite3-sys = { version = "*", features = ["bundled"] }
log = "*"
mime = "*"
r2d2 = "*"
serde = "*"
serde_json = "*"

[dev-dependencies]
