[workspace]
members = [
  "crates/client",
  "crates/core",
  "crates/core-json",
  "crates/core-api",
  "crates/core-api-json",
  "crates/usecases-sqlite-json",
  "crates/media",
  "crates/repo",
  "crates/repo-sqlite",
  "crates/storage-sqlite",
  "crates/usecases",
  "crates/usecases-sqlite",
  "crates/websrv-api",
  "webcli",
  "websrv",
]
# The webapp needs to be excluded from the workspace, because it is built
# for a different target and with a different build profile!
exclude = [ "webapp" ]

[patch.crates-io]
# Workspace crates
aoide-client = { path = "crates/client" }
aoide-core = { path = "crates/core" }
aoide-core-json = { path = "crates/core-json" }
aoide-core-api = { path = "crates/core-api" }
aoide-core-api-json = { path = "crates/core-api-json" }
aoide-media = { path = "crates/media" }
aoide-repo = { path = "crates/repo" }
aoide-repo-sqlite = { path = "crates/repo-sqlite" }
aoide-storage-sqlite = { path = "crates/storage-sqlite" }
aoide-usecases = { path = "crates/usecases" }
aoide-usecases-sqlite = { path = "crates/usecases-sqlite" }
aoide-usecases-sqlite-json = { path = "crates/usecases-sqlite-json" }
aoide-websrv-api = { path = "crates/websrv-api" }

# Unreleased crates
#triseratops = { git = "https://github.com/Holzhaus/triseratops", branch = "main" }

# Temporary patches
#mp4ameta = { branch = "master", git = "https://github.com/Saecki/rust-mp4ameta" }
#id3 = { branch = "master", git = "https://github.com/polyfloyd/rust-id3" }

[profile.dev]
opt-level = 2
split-debuginfo = "unpacked"

[profile.test]
inherits = "dev"

[profile.release]
opt-level = 3

[profile.profiling]
inherits = "release"
# Keep debug symbols for profiling -> results in huge binary!
debug = true

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
