# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[workspace]
members = [
  "crates/backend-embedded",
  "crates/backend-webapi-json",
  "crates/client",
  "crates/core",
  "crates/core-json",
  "crates/core-api",
  "crates/core-api-json",
  "crates/desktop-app",
  "crates/media",
  "crates/repo",
  "crates/repo-sqlite",
  "crates/search-index-tantivy",
  "crates/storage-sqlite",
  "crates/usecases",
  "crates/usecases-sqlite",
  "crates/websrv-warp-sqlite",
  "webcli",
  "websrv",
]
# The webapp needs to be excluded from the workspace, because it is built
# for a different target and with a different build profile!
exclude = [ "webapp" ]

[patch.crates-io]
# Workspace crates
aoide-backend-embedded = { path = "crates/backend-embedded" }
aoide-backend-webapi-json = { path = "crates/backend-webapi-json" }
aoide-client = { path = "crates/client" }
aoide-core = { path = "crates/core" }
aoide-core-json = { path = "crates/core-json" }
aoide-core-api = { path = "crates/core-api" }
aoide-core-api-json = { path = "crates/core-api-json" }
aoide-desktop-app = { path = "crates/desktop-app" }
aoide-media = { path = "crates/media" }
aoide-repo = { path = "crates/repo" }
aoide-repo-sqlite = { path = "crates/repo-sqlite" }
aoide-search-index-tantivy = { path = "crates/search-index-tantivy" }
aoide-storage-sqlite = { path = "crates/storage-sqlite" }
aoide-usecases = { path = "crates/usecases" }
aoide-usecases-sqlite = { path = "crates/usecases-sqlite" }
aoide-websrv-warp-sqlite = { path = "crates/websrv-warp-sqlite" }

# Unreleased crates
#triseratops = { git = "https://github.com/Holzhaus/triseratops", branch = "main" }

# Temporary patches
#mp4ameta = { git = "https://github.com/Saecki/rust-mp4ameta", branch = "master" }
#id3 = { git = "https://github.com/polyfloyd/rust-id3", branch = "master" }
#semval = { git = "https://github.com/slowtec/semval", branch = "main" }
#mpeg-audio-header = { git = "https://github.com/uklotzde/mpeg-audio-header", branch = "main" }
#discro = { git = "https://github.com/uklotzde/discro", branch = "main" }

[profile.dev]
opt-level = 2
split-debuginfo = "unpacked"

[profile.test]
inherits = "dev"

[profile.release]
opt-level = 3
lto = "thin"
strip = "debuginfo"

[profile.profiling]
inherits = "release"
# Keep debug symbols for profiling -> results in huge binary!
debug = true

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
strip = true
panic = "abort"
