[package]
name = "aoide"
version = "0.0.1"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
description = "Backend services for curating and enjoying your music"
keywords = ["music", "library", "management"]
publish = false

[workspace]
members = [
  "./",
  "aoide-core",
  "aoide-storage",
]

[patch.crates-io]
aoide-core = { path = "aoide-core" }
aoide-storage = { path = "aoide-storage" }

[dependencies]
aoide-core = { version = "*", path = "aoide-core" }
aoide-storage = { version = "*", path = "aoide-storage" }

actix = "*"
actix-web = "*"
clap = "*"
diesel = { version = "*", features = ["r2d2", "sqlite"] }
diesel_migrations =  { version = "*", features = ["sqlite"] }
env_logger = "*"
failure = { version = "*", features = ["std"] }
futures = "*"
hyper = "*"
libsqlite3-sys = { version = "*", features = ["bundled"] }
log = "*"
mime = "*"
serde = "*"
serde_json = "*"

[dev-dependencies]

[profile.release]
lto = true
