[package]
name = "aoide"
version = "0.0.9"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
description = "A web service for managing and exploring music collections"
keywords = ["music", "library", "management"]
publish = false
edition = "2018"

[workspace]
members = [
  "./",
  "domain",
  "storage",
]

[patch.crates-io]
aoide-domain = { path = "domain" }
aoide-storage = { path = "storage" }

[dependencies]
aoide-domain = "*"
aoide-storage = "*"
chrono = "*"
clap = "*"
diesel = { version = "*", features = ["r2d2", "sqlite"] }
diesel_migrations =  { version = "*", features = ["sqlite"] }
env_logger = "*"
failure = { version = "*", features = ["std"] }
futures = "*"
hyper = "*"
log = "^0.4"
mime = "^0.3"
serde = "*"
serde_json = "*"
tokio = "0.1"
warp = "*"

[dev-dependencies]
serde_urlencoded = "*"

[profile.release]
lto = true
codegen-units = 1
