[workspace]
members = [
  "crates/client",
  "crates/core",
  "crates/core-serde",
  "crates/core-ext",
  "crates/core-ext-serde",
  "crates/media",
  "crates/repo",
  "crates/repo-sqlite",
  "crates/usecases",
  "crates/websrv",
]

[patch.crates-io]
# Workspace crates
aoide-client = { path = "crates/client" }
aoide-core = { path = "crates/core" }
aoide-core-serde = { path = "crates/core-serde" }
aoide-core-ext = { path = "crates/core-ext" }
aoide-core-ext-serde = { path = "crates/core-ext-serde" }
aoide-media = { path = "crates/media" }
aoide-repo = { path = "crates/repo" }
aoide-repo-sqlite = { path = "crates/repo-sqlite" }
aoide-usecases = { path = "crates/usecases" }
aoide-websrv = { path = "crates/websrv" }

# Unreleased crates
triseratops = { git = "https://github.com/Holzhaus/triseratops.git", branch = "main" }
mp3-duration = { git = "https://github.com/aoide-org/mp3-duration.git", branch = "streaminfo" }

# Temporary patches
#mp4ameta = { branch = "master", git = "https://github.com/Saecki/rust-mp4ameta.git" }
#id3 = { branch = "master", git = "https://github.com/polyfloyd/rust-id3.git" }

[profile.dev]
split-debuginfo = "unpacked"

[profile.test]
split-debuginfo = "unpacked"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
# Keep debug symbols, e.g. for profiling -> results in huge binary!
#debug = true
