[package]
name = "aoide"
version = "0.8.0"
license-file = "LICENSE.md"
description = "A web service for managing and exploring music collections"
keywords = ["music", "collection"]
publish = false
edition = "2018"

[workspace]
members = [
  "./",
  "client",
  "core",
  "core-serde",
  "media",
  "repo",
  "repo-sqlite",
  "usecases",
]

[patch.crates-io]
aoide-client = { path = "./client" }
aoide-core = { path = "./core" }
aoide-core-serde = { path = "./core-serde" }
aoide-media = { path = "./media" }
aoide-repo = { path = "./repo" }
aoide-repo-sqlite = { path = "./repo-sqlite" }
aoide-usecases = { path = "./usecases" }
triseratops = { git = "https://github.com/Holzhaus/triseratops.git", branch = "main" }
mp3-duration = { git = "https://github.com/aoide-org/mp3-duration.git", branch = "streaminfo" }
#mp4ameta = { branch = "master", git = "https://github.com/Saecki/rust-mp4ameta.git" }
#id3 = { branch = "master", git = "https://github.com/polyfloyd/rust-id3.git" }

[dependencies]
anyhow = "*"
aoide-core = "*"
aoide-core-serde = "*"
aoide-media = "*"
aoide-repo = "*"
aoide-repo-sqlite = "*"
aoide-usecases = "*"
blake3 = "*"
chrono = { version = "*", default-features = false, features = ["clock", "serde"] }
diesel = { version = "*", default-features = false, features = ["r2d2", "sqlite"] }
diesel_migrations =  { version = "*", default-features = false, features = ["sqlite"] }
dotenv = "*"
log = "*"
percent-encoding = "*"
r2d2 = "*"
semval = { version = ">=0.1.7" }
serde = "*"
serde_json = "*"
thiserror = "*"
tokio = { version = "*", default-features = false, features = ["macros", "rt-multi-thread", "signal"] }
tracing = { version = "*", features = ["log"] }
tracing-bunyan-formatter = "*"
tracing-subscriber = { version = "*", features = ["registry", "env-filter"] }
url = { version = "*", features = ["serde"] }
warp = { version = "*", default-features = false }

# This is not needed as a direct, standalone dependency but should
# enforce to always use the latest and greatest rusqlite/sqlite3 version!
rusqlite =  { version = ">=0.25.3", default-features = false }

[features]
default = []

[dev-dependencies]
serde_urlencoded = "*"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
# Keep debug symbols, e.g. for profiling -> results in huge binary!
#debug = true
