[package]
name = "aoide"
version = "0.8.0"
license-file = "LICENSE.md"
description = "Manage and explore your music collections"
keywords = ["music", "collection"]
publish = false
rust-version = "1.56"
edition = "2021"

[workspace]
members = [
  ".",
  "client",
  "core",
  "core-serde",
  "core-ext",
  "core-ext-serde",
  "media",
  "repo",
  "repo-sqlite",
  "usecases",
  "websrv",
]

[patch.crates-io]
aoide-client = { path = "./client" }
aoide-core = { path = "./core" }
aoide-core-serde = { path = "./core-serde" }
aoide-core-ext = { path = "./core-ext" }
aoide-core-ext-serde = { path = "./core-ext-serde" }
aoide-media = { path = "./media" }
aoide-repo = { path = "./repo" }
aoide-repo-sqlite = { path = "./repo-sqlite" }
aoide-usecases = { path = "./usecases" }
aoide-websrv = { path = "./websrv" }
triseratops = { git = "https://github.com/Holzhaus/triseratops.git", branch = "main" }
mp3-duration = { git = "https://github.com/aoide-org/mp3-duration.git", branch = "streaminfo" }
#mp4ameta = { branch = "master", git = "https://github.com/Saecki/rust-mp4ameta.git" }
#id3 = { branch = "master", git = "https://github.com/polyfloyd/rust-id3.git" }

[dependencies]
aoide-client = { version = "*", default_features = false, optional = true }
aoide-websrv = { version = "*", default_features = false, optional = true }

[features]
default = []
with-client = ["aoide-client"]
with-websrv = ["aoide-websrv"]
with-webapp = ["with-websrv", "aoide-websrv/with-webapp"]

[profile.dev]
split-debuginfo = "unpacked"

[profile.test]
split-debuginfo = "unpacked"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
# Keep debug symbols, e.g. for profiling -> results in huge binary!
#debug = true
