[workspace]
members = [
  "crates/client",
  "crates/core",
  "crates/core-serde",
  "crates/core-ext",
  "crates/core-ext-serde",
  "crates/jsonapi-sqlite",
  "crates/media",
  "crates/repo",
  "crates/repo-sqlite",
  "crates/storage-sqlite",
  "crates/usecases",
  "crates/usecases-sqlite",
  "websrv",
]
# The webapp needs to be excluded from the workspace, because it is built
# for a different target and with a different build profile!
exclude = [ "webapp" ]

[patch.crates-io]
# Workspace crates
aoide-client = { path = "crates/client" }
aoide-core = { path = "crates/core" }
aoide-core-serde = { path = "crates/core-serde" }
aoide-core-ext = { path = "crates/core-ext" }
aoide-core-ext-serde = { path = "crates/core-ext-serde" }
aoide-jsonapi-sqlite = { path = "crates/jsonapi-sqlite" }
aoide-media = { path = "crates/media" }
aoide-repo = { path = "crates/repo" }
aoide-repo-sqlite = { path = "crates/repo-sqlite" }
aoide-storage-sqlite = { path = "crates/storage-sqlite" }
aoide-usecases = { path = "crates/usecases" }
aoide-usecases-sqlite = { path = "crates/usecases-sqlite" }

# Unreleased crates
triseratops = { git = "https://github.com/Holzhaus/triseratops.git", branch = "main" }
mp3-duration = { git = "https://github.com/aoide-org/mp3-duration.git", branch = "streaminfo" }

# Temporary patches
#mp4ameta = { branch = "master", git = "https://github.com/Saecki/rust-mp4ameta.git" }
#id3 = { branch = "master", git = "https://github.com/polyfloyd/rust-id3.git" }

[profile.dev]
split-debuginfo = "unpacked"

[profile.test]
inherits = "dev"

[profile.release]
opt-level = 3

[profile.profiling]
inherits = "release"
# Keep debug symbols for profiling -> results in huge binary!
debug = true

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
