[package]
name = "aoide"
version = "0.0.1"
authors = [ "Uwe Klotz <uwe.klotz@gmail>" ]
description = "Backend services for curating and enjoying your music"
publish = false

[dependencies]
base64 = { version = "*" }
chrono = { version = "*", features = ["serde"] }
diesel = { version = "*", features = ["chrono", "sqlite"] }
diesel_migrations =  { version = "*", features = ["sqlite"] }
env_logger = "*"
log = "*"
mime_guess = "*"
ring = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
uuid = { version = "*", features = ["serde", "v1", "v4"] }
