[package]
name = "aoide"
version = "0.0.1"
authors = [ "Uwe Klotz <uwe.klotz@gmail>" ]
description = "Backend services for curating and enjoying your music"
publish = false

[workspace]
members = [
  "./",
  "aoide-core",
]

[patch.crates-io]
aoide-core = { path = "aoide-core" }

[dependencies]
aoide-core = { version = "*", path = "aoide-core" }

chrono = { version = "*", features = ["serde"] }
clap = "*"
diesel = { version = "*", features = ["chrono", "sqlite"] }
diesel_migrations =  { version = "*", features = ["sqlite"] }
env_logger = "*"
failure = { version = "*", features = ["std"] }
#futures = "*"
futures = "0.1.*"
gotham = "*"
gotham_derive = "*"
hyper = "*"
log = "*"
mime = ">= 0.3"
percent-encoding = "*"
r2d2 = "*"
r2d2-diesel = "*"
rmp-serde = "*"
serde = "*"
serde_cbor = "*"
serde_derive = "*"
serde_json = "*"
uuid = "*"

[dev-dependencies]

