msrv = "1.54"

disallowed-methods = [
    # Use the faster, simpler, and non-poisonable primitives in `parking_lot` instead
    # TODO: Move to disallowed-types after switching to Rust 1.55
    "std::sync::Mutex::new",
    "std::sync::RwLock::new",
    "std::sync::CondVar::new",
]

# TODO: Uncomment after switching to Rust 1.55
#disallowed-types = [
#    # Probably not suitable for any use case
#    "std::collections::LinkedList"
#]
