# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: CC0-1.0

[toolchain]
channel = "stable"
profile = "minimal"
components = [ "rustfmt", "clippy" ]
