[package]
name = "aoide-media"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
blake3 = { version = "1.3.1", features = ["traits-preview"] }
bitflags = "1.3.2"
bytes = "1.1.0"
digest = "0.10.3"
image = "0.24.2"
log = "0.4.16"
mime = "0.3.16"
mime_guess = "2.0.4"
nom = "7.1.1"
num-traits = "0.2.14"
semval = "0.3.0"
serde_json = "1.0.79"
thiserror = "1.0.30"
time = { version = "0.3.9", features = ["parsing"] }
triseratops = "0.0.2"
url = "2.2.2"
walkdir = "2.3.2"

# Workspace dependencies
aoide-core = "=0.8.0"
aoide-core-json = "=0.8.0"

# Optional dependencies
id3 = { version = "1.0.2", optional = true }
lewton = { version = "0.10.2", optional = true }
metaflac = { version = "0.2.5", optional = true }
mpeg-audio-header = { version = "0.0.2", optional = true }
mp4ameta = { version = "0.11.0", optional = true }
opus_headers = { version = "0.1.2", optional = true }

[features]
# TODO: Add support for AIFF files
fmt-aiff = [ "id3" ]
fmt-flac = [ "metaflac" ]
fmt-mp4 = [ "mp4ameta" ]
fmt-mp3 = [ "id3", "mpeg-audio-header" ]
fmt-ogg = [ "lewton", "metaflac" ] # metaflac for decoding FLAC picture blocks
fmt-opus = [ "opus_headers", "metaflac" ] # metaflac for decoding FLAC picture blocks
# TODO: Add support for WAV files
fmt-wav = [ "id3" ]
default = [ "fmt-aiff", "fmt-flac", "fmt-mp3", "fmt-mp4", "fmt-ogg", "fmt-opus", "fmt-wav" ]
