[package]
name = "aoide-media"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "*"
base64 = "*"
blake3 = { version = "*", features = ["traits-preview"] }
bitflags = "*"
bytes = "*"
chrono = { version = "*", default-features = false }
digest = "*"
image = "*"
log = "*"
mime = "*"
mime_guess = "*"
nom = "*"
num-traits = "*"
path-slash = "*"
semval = "*"
serde_json = "*"
thiserror = "*"
triseratops = "*"
url = "*"
walkdir = "*"

# Workspace dependencies
aoide-core = "*"
aoide-core-json = "*"

# Optional dependencies
id3 = { version = ">=0.6", optional = true }
lewton = { version = "*", optional = true }
metaflac = { version = "*", optional = true }
mpeg-audio-header = { version = "*", optional = true }
mp4ameta = { version = ">=0.11", optional = true }
opus_headers = { version = "*", optional = true }

[features]
# TODO: Add support for AIFF files
fmt-aiff = [ "id3" ]
fmt-flac = [ "metaflac" ]
fmt-mp4 = [ "mp4ameta" ]
fmt-mp3 = [ "id3", "mpeg-audio-header" ]
fmt-ogg = [ "lewton", "metaflac" ] # metaflac for decoding FLAC picture blocks
fmt-opus = [ "opus_headers", "metaflac" ] # metaflac for decoding FLAC picture blocks
# TODO: Add support for WAV files
fmt-wav = [ "id3" ]
default = [ "fmt-aiff", "fmt-flac", "fmt-mp3", "fmt-mp4", "fmt-ogg", "fmt-opus", "fmt-wav" ]
