# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-media"
description = "aoide - Import/export of metadata for media sources and tracks"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
blake3 = { version = "1.3", features = ["traits-preview"] }
bitflags = "1.3"
bytes = "1.2"
digest = "0.10"
image = "0.24"
log = "0.4"
mime = "0.3"
mime_guess = "2.0"
nom = "7.1"
num-traits = "0.2"
semval = "0.4"
thiserror = "1.0"
time = { version = "0.3", features = ["parsing"] }
url = "2.2"
walkdir = "2.3"

# Dependencies (optional)
id3 = { version = "1.3", optional = true }
lewton = { version = "0.10", optional = true }
metaflac = { version = "0.2", optional = true }
mpeg-audio-header = { version = "0.0.4", optional = true }
mp4ameta = { version = "0.11", optional = true }
opus_headers = { version = "0.1", optional = true }

# Dependencies (optional): gigtag
gigtag = { version = "0.0.13", optional = true }
compact_str = { version = "0.5", optional = true }

# Dependencies (optional): serato-markers
triseratops = { version = "0.0.2", optional = true }

# Workspace dependencies
aoide-core = "=0.8.0"

[features]
default = ["all"]
all = ["fmt-all", "gigtag", "serato-markers"]
fmt-all = [
    "fmt-aiff",
    "fmt-flac",
    "fmt-mp3",
    "fmt-mp4",
    "fmt-ogg",
    "fmt-opus",
    "fmt-wav",
]
fmt-aiff = ["id3"]
fmt-flac = ["metaflac"]
fmt-mp3 = ["id3", "mpeg-audio-header"]
fmt-mp4 = ["mp4ameta"]
fmt-ogg = ["lewton", "metaflac"] # metaflac for decoding FLAC picture blocks
fmt-opus = [
    "opus_headers",
    "metaflac",
] # metaflac for decoding FLAC picture blocks
fmt-wav = ["id3"]
gigtag = ["dep:gigtag", "compact_str"]
serato-markers = ["triseratops"]
