[package]
name = "aoide-repo"
version = "0.1.0"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
publish = false
edition = "2018"

[dependencies]
aoide-core = "*"
chrono = { version = "*" }
failure = "*"
log = "*"
mime = "*"
percent-encoding = "*"
rand = "*"
