# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-storage-sqlite"
description = "aoide - Utilities for an SQLite storage backend"
publish = false
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.86"
diesel = { version = "2.2.2", default-features = false, features = [
    "r2d2",
    "sqlite",
] }
log = "0.4.22"
r2d2 = "0.8.10"
thiserror = "1.0.63"

# Optional: Serde for serialization of config files.
serde = { version = "1.0.207", optional = true, features = ["derive"] }

# Feature "sqlite-bundled"
# Bundle SQLite code to prevent dynamic linking.
# The pinned version must be compatible with diesel!
libsqlite3-sys = { version = "=0.29.0", optional = true, features = [
    "bundled",
] }

# Feature "tokio"
tokio = { version = "1.39.2", optional = true, default-features = false, features = [
    "macros",
    "rt",
    "sync",
    "time",
] }

[features]
default = ["sqlite-bundled", "tokio"]
serde = ["dep:serde"]
sqlite-bundled = ["dep:libsqlite3-sys"]
tokio = ["dep:tokio"]
