[package]
name = "aoide-storage-sqlite"
description = "aoide - Utilities for an SQLite storage backend"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
diesel = { version = "1.4.8", default-features = false, features = ["r2d2", "sqlite"] }
# Bundle SQLite code to prevent dynamic linking.
# The pinned version must be compatible with diesel!
libsqlite3-sys = { version = "0.22.2", features = ["bundled"] }
log = "0.4.17"
r2d2 = "0.8.9"
thiserror = "1.0.31"

serde = { version = "1.0.137", optional = true, features = ["derive"] }
tokio = { version = "1.19.0", optional = true, default-features = false, features = ["macros", "rt", "sync", "time"] }

[features]
default = ["tokio"]
serde = ["dep:serde"]
tokio = ["dep:tokio"]
