[package]
name = "aoide-storage-sqlite"
description = "Utilities for an SQLite storage backend"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1"
diesel = { version = "1.4.8", default-features = false, features = ["r2d2", "sqlite"] }
# Bundle SQLite code to prevent dynamic linking.
# The pinned version must be compatible with diesel!
libsqlite3-sys = { version = "0.22", features = ["bundled"] }
log = "0.4"
r2d2 = "0.8"
thiserror = "1"

tokio = { version = "*", optional = true, default-features = false, features = ["macros", "rt"] }

[features]
default = []
with-tokio = ["tokio"]
