# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-storage-sqlite"
description = "aoide - Utilities for an SQLite storage backend"
repository = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = "1.0.72"
diesel = { version = "2.1.0", default-features = false, features = ["r2d2", "sqlite"] }
log = "0.4.19"
r2d2 = "0.8.10"
thiserror = "1.0.44"

# Feature "serde"
serde = { version = "1.0.182", optional = true, features = ["derive"] }

# Feature "sqlite-bundled"
# Bundle SQLite code to prevent dynamic linking.
# The pinned version must be compatible with diesel!
libsqlite3-sys = { version = "0.26.0", optional = true, features = ["bundled"] }

# Feature "tokio"
tokio = { version = "1.29.1", optional = true, default-features = false, features = ["macros", "rt", "sync", "time"] }

[features]
default = ["sqlite-bundled", "tokio"]
serde = ["dep:serde"]
sqlite-bundled = ["dep:libsqlite3-sys"]
tokio = ["dep:tokio"]
