# SPDX-FileCopyrightText: Copyright (C) 2018-2025 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-storage-sqlite"
description = "aoide - Utilities for an SQLite storage backend"
publish = false
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
diesel = { workspace = true, features = ["r2d2"] }
log.workspace = true
r2d2 = "0.8.10"
thiserror.workspace = true

# Optional: Serde for serialization of config files.
serde = { workspace = true, optional = true, features = ["derive"] }

# Feature "sqlite-bundled"
# Bundle SQLite code to prevent dynamic linking.
# The pinned version must be compatible with diesel!
libsqlite3-sys = { version = "=0.33.0", optional = true, default-features = false, features = [
  "bundled",
] }

# Feature "tokio"
tokio = { workspace = true, optional = true, features = ["macros", "rt", "sync", "time"] }

[features]
default = ["sqlite-bundled", "tokio"]
serde = ["dep:serde"]
sqlite-bundled = ["dep:libsqlite3-sys"]
tokio = ["dep:tokio"]
