# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-storage-sqlite"
description = "aoide - Utilities for an SQLite storage backend"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
diesel = { version = "1.4", default-features = false, features = ["r2d2", "sqlite"] }
# Bundle SQLite code to prevent dynamic linking.
# The pinned version must be compatible with diesel!
libsqlite3-sys = { version = "0.22", features = ["bundled"] }
log = "0.4"
r2d2 = "0.8"
thiserror = "1.0"

serde = { version = "1.0", optional = true, features = ["derive"] }
tokio = { version = "1.20", optional = true, default-features = false, features = ["macros", "rt", "sync", "time"] }

[features]
default = ["tokio"]
serde = ["dep:serde"]
tokio = ["dep:tokio"]
