[package]
name = "aoide-storage-sqlite"
description = "Utilities for an SQLite storage backend"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "*"
diesel = { version = "*", default-features = false, features = ["r2d2", "sqlite"] }
log = "*"
r2d2 = "*"
thiserror = "*"

tokio = { version = "*", optional = true, default-features = false, features = ["macros", "rt"] }

[features]
default = []
with-tokio = ["tokio"]
