# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-storage-sqlite"
description = "aoide - Utilities for an SQLite storage backend"
version.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = "1.0.65"
diesel = { version = "2.0.0", default-features = false, features = ["r2d2", "sqlite"] }
# Bundle SQLite code to prevent dynamic linking.
# The pinned version must be compatible with diesel!
# Could be avoided by adding aoide-storage-sqlite as a dependency
# instead, but currently nothing from this crate is actually used.
libsqlite3-sys = { version = "0.25.1", features = ["bundled"] }
log = "0.4.17"
r2d2 = "0.8.10"
thiserror = "1.0.36"

serde = { version = "1.0.145", optional = true, features = ["derive"] }
tokio = { version = "1.21.1", optional = true, default-features = false, features = ["macros", "rt", "sync", "time"] }

[features]
default = ["tokio"]
serde = ["dep:serde"]
tokio = ["dep:tokio"]
