# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-client"
description = "aoide - [experimental] Unidirectional dataflow client components"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"], optional = true }
serde_json = "1.0.91"
serde_urlencoded = "0.7.1"
static_assertions = "1.1.0"

# Optional dependencies for feature tokio
tokio = { version = "1.24.2", optional = true, default-features = false, features = ["sync"] }

# Optional dependencies for feature webapi-backend
reqwest = { version = "0.11.14", optional = true, default-features = false, features = [
    "rustls-tls",
] }

# Workspace dependencies
aoide-core = { version = "=0.8.0", features = ["serde"] }
aoide-core-json = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-core-api-json = { version = "=0.8.0", features = ["frontend"] }

[features]
default = []
webapi-backend = ["reqwest"]
tokio = ["dep:tokio"]
