[package]
name = "aoide-client"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "*"
bytes = "*"
log = "*"
serde = { version = "1", features = ["derive"], optional = true }
serde_json = "*"
serde_urlencoded = "*"
static_assertions = "*"

# Optional dependencies for feature with-tokio
tokio = { version = "*", optional = true, default-features = false }

# Optional dependencies for feature with-reqwest
reqwest = { version = "*", optional = true, default-features = false, features = ["rustls-tls"] }

# Workspace dependencies
aoide-core = "*"
aoide-core-json = "*"
aoide-core-api = "*"
aoide-core-api-json = { version = "*", features = ["frontend"] }

[features]
default = []
with-reqwest = ["reqwest"]
with-tokio = ["tokio"]
