[package]
name = "aoide-client"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "*"
bytes = "*"
reqwest = { version = "*", default-features = false, features = ["rustls-tls"] }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = "*"
serde_urlencoded = "*"
tokio = { version = "*", default-features = false }
tracing = { version = "*", features = ["log"] }

# Workspace dependencies
aoide-core = "*"
aoide-core-json = "*"
aoide-core-api = "*"
aoide-core-api-json = { version = "*", features = ["frontend"] }

[dev-dependencies]
clap = "*"
env_logger = { version = ">=0.9" }
tokio = { version = "*", default-features = false, features = ["macros", "rt-multi-thread", "signal"] }
