# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-client"
description = "aoide - [experimental] Unidirectional dataflow client components"
version.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = "1.0"
bytes = "1.2"
log = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = "1.0"
serde_urlencoded = "0.7"
static_assertions = "1.1"

# Optional dependencies for feature tokio
tokio = { version = "1.21", optional = true, default-features = false, features = ["sync"] }

# Optional dependencies for feature webapi-backend
reqwest = { version = "0.11", optional = true, default-features = false, features = [
    "rustls-tls",
] }

# Workspace dependencies
aoide-core = { version = "=0.8.0", features = ["serde"] }
aoide-core-json = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-core-api-json = { version = "=0.8.0", features = ["frontend"] }

[features]
default = []
webapi-backend = ["reqwest"]
tokio = ["dep:tokio"]
