[package]
name = "aoide-client"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "*"
bytes = "*"
log = "*"
reqwest = { version = "*", default-features = false, features = ["rustls-tls"] }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = "*"
serde_urlencoded = "*"
static_assertions = "*"
tokio = { version = "*", default-features = false }

# Workspace dependencies
aoide-core = "*"
aoide-core-json = "*"
aoide-core-api = "*"
aoide-core-api-json = { version = "*", features = ["frontend"] }
