[package]
name = "aoide-client"
version = "0.8.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
bytes = "1.1.0"
log = "0.4.14"
serde = { version = "1.0.136", features = ["derive"], optional = true }
serde_json = "1.0.79"
serde_urlencoded = "0.7.1"
static_assertions = "1.1.0"

# Optional dependencies for feature with-tokio
tokio = { version = "1.17.0", optional = true, default-features = false }

# Optional dependencies for feature with-reqwest
reqwest = { version = "0.11.9", optional = true, default-features = false, features = ["rustls-tls"] }

# Workspace dependencies
aoide-core = "*"
aoide-core-json = "*"
aoide-core-api = "*"
aoide-core-api-json = { version = "*", features = ["frontend"] }

[features]
default = []
with-reqwest = ["reqwest"]
with-tokio = ["tokio"]
