[package]
name = "aoide-core-api-json"
description = "aoide - JSON mapping for aoide-core-api boundary types"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
url = { version = "2.2.2", features = ["serde"] }

# JSON Schema (optional)
schemars = { version = "0.8.10", optional = true, features = ["url"] }

# Workspace dependencies
aoide-core = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-core-json = "=0.8.0"

[features]
default = []
frontend = []
backend = []
schemars = ["dep:schemars", "aoide-core-json/schemars"]
