[package]
name = "aoide-core-api-json"
description = "JSON types for aoide-core APIs"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "*"
serde = { version = "*", features = ["derive"] }
url = { version = "*", features = ["serde"] }

# Workspace dependencies
aoide-core = "*"
aoide-core-json = "*"
aoide-core-api = "*"

[features]
default = []
frontend = []
backend = []
