# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core-api-json"
description = "aoide - JSON mapping for aoide-core-api boundary types"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.69"
serde = { version = "1.0.152", features = ["derive"] }
url = { version = "2.3.1", features = ["serde"] }

# JSON Schema (optional)
schemars = { version = "0.8.12", optional = true, features = ["url"] }

# Workspace dependencies
aoide-core = { version = "=0.8.0", features = ["serde"] }
aoide-core-api = "=0.8.0"
aoide-core-json = "=0.8.0"

[features]
default = []
frontend = []
backend = []
json-schema = ["schemars", "aoide-core/json-schema", "aoide-core-json/json-schema"]
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["aoide-core/js", "aoide-core-api/js", "aoide-core-json/js"]
