# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-backend-embedded"
description = "aoide - Asynchronous API for an embedded, serverless backend (no JSON/HTTP)"
repository = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = "1.0.76"
diesel = { version = "2.1.4", default-features = false, features = ["sqlite"] }
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.51"

# Workspace dependencies
aoide-core = { version = "=0.8.0", path = "../core" }
aoide-core-api = { version = "=0.8.0", path = "../core-api" }
aoide-media-file = { version = "=0.8.0", path = "../media-file" }
aoide-repo = { version = "=0.8.0", path = "../repo" }
aoide-repo-sqlite = { version = "=0.8.0", path = "../repo-sqlite" }
aoide-storage-sqlite = { version = "=0.8.0", path = "../storage-sqlite", features = ["serde", "tokio"] }
aoide-usecases = { version = "=0.8.0", path = "../usecases" }
aoide-usecases-sqlite = { version = "=0.8.0", path = "../usecases-sqlite" }

# Optional: Tantivy search index
aoide-search-index-tantivy = { version = "=0.8.0", path = "../search-index-tantivy", optional = true }
tantivy = { version = "0.21.1", optional = true }

[features]
default = []
tantivy = ["dep:aoide-search-index-tantivy", "dep:tantivy"]
