# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-backend-embedded"
description = "aoide - Asynchronous API for an embedded, serverless backend (no JSON/HTTP)"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.69"
diesel = { version = "2.0.3", default-features = false, features = ["sqlite"] }
log = "0.4.17"
serde = { version = "1.0.154", features = ["derive"] }
thiserror = "1.0.39"

# Workspace dependencies
aoide-core = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-media = "=0.8.0"
aoide-repo = "=0.8.0"
aoide-repo-sqlite = "=0.8.0"
aoide-storage-sqlite = { version = "=0.8.0", features = ["serde", "tokio"] }
aoide-usecases = "=0.8.0"
aoide-usecases-sqlite = "=0.8.0"

# Optional: Tantivy search index
aoide-search-index-tantivy = { version = "=0.8.0", optional = true }
tantivy = { version = "0.19.2", optional = true }

[features]
default = []
tantivy = ["aoide-search-index-tantivy", "dep:tantivy"]
