# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-desktop-app"
description = "aoide - Desktop app support"
repository = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = "1.0.71"
discro = { version = "0.8.2", features = ["tokio"] }
highway = { version = "1.0.0" }
log = "0.4.18"
rfd = { version = "0.11.4", default-features = false, features = ["xdg-portal"] }
ron = "0.8.0"
serde = { version = "1.0.164", features = ["derive"] }
tokio = { version = "1.28.2", default-features = false }
unnest = "0.3.1"
url = { version = "2.4.0", features = ["serde"] }

# Workspace dependencies
aoide-backend-embedded = { version = "=0.8.0", path = "../backend-embedded" }
aoide-core = { version = "=0.8.0", path = "../core" }
aoide-core-api = { version = "=0.8.0", path = "../core-api" }
aoide-media-file = { version = "=0.8.0", path = "../media-file" }
aoide-repo = { version = "=0.8.0", path = "../repo" }
aoide-storage-sqlite = { version = "=0.8.0", path = "../storage-sqlite", features = ["serde", "tokio"] }
