# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-desktop-app"
description = "aoide - Desktop app support"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.69"
discro = { version = "0.8.0", features = ["tokio"] }
unnest = "0.3.1"
log = "0.4.17"
rfd = { version = "0.11.0", default-features = false, features = ["xdg-portal"] }
ron = "0.8.0"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.25.0", default-features = false }
url = { version = "2.3.1", features = ["serde"] }
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }

# Workspace dependencies
aoide-backend-embedded = "=0.8.0"
aoide-core = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-media = "=0.8.0"
aoide-repo = "=0.8.0"
aoide-storage-sqlite = { version = "=0.8.0", features = ["serde", "tokio"] }
