# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-desktop-app"
description = "aoide - Desktop app support"
repository = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = "1.0.80"
discro = { version = "0.29.1", features = ["tokio"] }
highway = { version = "1.1.0" }
log = "0.4.20"
ron = "0.8.1"
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.36.0", default-features = false }
unnest = "0.3.1"
url = { version = "2.5.0", features = ["serde"] }

# Workspace dependencies
aoide-backend-embedded = { version = "=0.8.0", path = "../backend-embedded", features = [
    "tokio",
] }
aoide-core = { version = "=0.8.0", path = "../core" }
aoide-core-api = { version = "=0.8.0", path = "../core-api" }
aoide-media-file = { version = "=0.8.0", path = "../media-file" }
aoide-repo = { version = "=0.8.0", path = "../repo" }
aoide-storage-sqlite = { version = "=0.8.0", path = "../storage-sqlite", features = [
    "serde",
    "tokio",
] }

[dependencies.rfd]
version = "0.13.0"
optional = true
default-features = false
features = ["tokio", "xdg-portal"]

[features]
default = []
async-file-dialog = ["dep:rfd"]
