# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-desktop-app"
description = "aoide - Desktop app support"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
publish = false

[dependencies]
anyhow = "1.0.70"
discro = { version = "0.8.0", features = ["tokio"] }
highway = { version = "1.0.0" }
log = "0.4.17"
rfd = { version = "0.11.3", default-features = false, features = ["xdg-portal"] }
ron = "0.8.0"
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.27.0", default-features = false }
unnest = "0.3.1"
url = { version = "2.3.1", features = ["serde"] }

# Workspace dependencies
aoide-backend-embedded = { path = "../backend-embedded" }
aoide-core = { path = "../core" }
aoide-core-api = { path = "../core-api" }
aoide-media = { path = "../media" }
aoide-repo = { path = "../repo" }
aoide-storage-sqlite = { path = "../storage-sqlite", features = ["serde", "tokio"] }
