[package]
name = "aoide-core"
version = "0.0.9"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
publish = false
edition = "2018"

[dependencies]
bs58 = "*"
chrono = "*"
lazy_static = "*"
num-traits = "*"
rand = "*"
semval = "*"
smallvec = "*"
