[package]
name = "aoide-core"
version = "0.0.9"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
publish = false
edition = "2018"

[dependencies]
# TODO: Replace validation with a lightweight solution that does
# not depend on serde!
validator = { version = "*", default-features = false }
validator_derive = "*"
