[package]
name = "aoide-core"
version = "0.1.1"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
publish = false
edition = "2018"

[dependencies]
bs58 = "*"
chrono = { version = "*", default-features = false }
lazy_static = "*"
num-traits = "*"
rand = "*"
semval = "*"

[dev-dependencies]
criterion = "*"
chrono = { version = "*", default-features = false, features = ["clock"] }
uuid = { version = "*", features = ["v4"] }

[[bench]]
name = "entity_uid_benchmark"
harness = false
