[package]
name = "aoide-core"
version = "0.0.2"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
publish = false
edition = "2018"

[dependencies]
bs58 = "*"
chrono = { version = "*", features = ["serde"] }
failure = "*"
lazy_static = "*"
log = "*"
mime = "*"
rand = "*"
serde = { version = "*", features = ["derive"] }

[dev-dependencies]
mime_guess = "*"
serde_json = "*"
criterion = "*"
uuid = { version = "*", features = ["v4"] }

[[bench]]
name = "entity_uid_benchmark"
harness = false
