# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-webcli"
description = "aoide - Media tracker CLI for web server"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = "3.2"
env_logger = "0.9"
log = "0.4"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
tokio = { version = "1.21", default-features = false, features = ["macros", "fs", "rt-multi-thread", "signal"] }

# Workspace dependencies
aoide-client = { version = "=0.8.0", features = ["webapi-backend", "tokio"] }
aoide-core = "=0.8.0"
aoide-core-json = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-core-api-json = { version = "=0.8.0", features = ["frontend"] }
