[package]
name = "aoide-webcli"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "*"
clap = "*"
env_logger = { version = ">=0.9" }
tokio = { version = "*", default-features = false, features = ["macros", "rt-multi-thread", "signal"] }
tracing = { version = "*", features = ["log"] }

# Workspace dependencies
aoide-client = "*"
aoide-core = "*"
aoide-core-json = "*"
aoide-core-api = "*"
aoide-core-api-json = { version = "*", features = ["frontend"] }
