# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-webcli"
description = "aoide - Media tracker CLI for web server"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.68"
clap = "4.0.32"
env_logger = "0.10.0"
log = { version = "0.4.17", features = ["release_max_level_debug"] }
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0.91"
serde_urlencoded = "0.7.1"
tokio = { version = "1.23.0", default-features = false, features = ["macros", "fs", "rt-multi-thread", "signal"] }

# Workspace dependencies
aoide-client = { version = "=0.8.0", features = ["webapi-backend", "tokio"] }
aoide-core = "=0.8.0"
aoide-core-json = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-core-api-json = { version = "=0.8.0", features = ["frontend"] }
