[package]
name = "aoide-webcli"
version = "0.8.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
clap = "3.1.6"
env_logger = "0.9.0"
log = "0.4.16"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0.79"
serde_urlencoded = "0.7.1"
tokio = { version = "1.17.0", default-features = false, features = ["macros", "fs", "rt-multi-thread", "signal"] }

# Workspace dependencies
aoide-client = { version = "*", features = ["with-webapi-backend", "with-tokio-runtime"] }
aoide-core = "*"
aoide-core-json = "*"
aoide-core-api = "*"
aoide-core-api-json = { version = "*", features = ["frontend"] }
