[package]
name = "aoide-webcli"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "*"
clap = "*"
env_logger = "*"
log = "*"
reqwest = { version = "*", default-features = false, features = ["rustls-tls"] }
serde_json = "*"
serde_urlencoded = "*"
tokio = { version = "*", default-features = false, features = ["macros", "fs", "rt-multi-thread", "signal"] }

# Workspace dependencies
aoide-client = { version = "*", features = ["with-reqwest", "with-tokio"] }
aoide-core = "*"
aoide-core-json = "*"
aoide-core-api = "*"
aoide-core-api-json = { version = "*", features = ["frontend"] }
