[package]
name = "aoide-repo"
description = "Types and traits for persistent storage"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "*"
num-derive = "*"
num-traits = "*"
paste = "*"
rand = "*"
semval = "*"
thiserror = "*"

# Workspace dependencies
aoide-core = "*"
aoide-core-api = "*"

[features]
default = []
