# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-repo"
description = "aoide - Storage-agnostic repository types and traits for the backend"
publish = false
version = "0.0.0"
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = "1.0.86"
paste = "1.0.15"
rand = "0.8.5"
thiserror = "1.0.61"

# Workspace dependencies
aoide-core = { version = "=0.0.0", path = "../core" }
aoide-core-api = { version = "=0.0.0", path = "../core-api" }
