[package]
name = "aoide-repo"
description = "Types and traits for persistent storage"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1"
num-derive = "0.3"
num-traits = "0.2"
paste = "1.0"
rand = "0.8"
semval = "0.2"
thiserror = "1"

# Workspace dependencies
aoide-core = "*"
aoide-core-api = "*"

[features]
default = []
