# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-repo"
description = "aoide - Storage-agnostic repository types and traits for the backend"
repo = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = "1.0.70"
num-derive = "0.3.3"
num-traits = "0.2.15"
paste = "1.0.12"
rand = "0.8.5"
thiserror = "1.0.40"

# Workspace dependencies
aoide-core = { version = "=0.8.0", path = "../core" }
aoide-core-api = { version = "=0.8.0", path = "../core-api" }

[features]
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["aoide-core/js", "aoide-core-api/js"]
