# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-repo"
description = "aoide - Storage-agnostic repository types and traits for the backend"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.58"
num-derive = "0.3.3"
num-traits = "0.2.15"
paste = "1.0.7"
rand = "0.8.5"
semval = "0.4.0"
thiserror = "1.0.31"

# Workspace dependencies
aoide-core = "=0.8.0"
aoide-core-api = "=0.8.0"

[features]
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["aoide-core/js", "aoide-core-api/js"]
