# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-search-index-tantivy"
description = "aoide - [experimental] Full-text search index based on Tantivy"
repository = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = "1.0.71"
num-traits = "0.2.15"
log = "0.4.18"
tantivy = "0.20.0"
thiserror = "1.0.40"

# Workspace dependencies
aoide-core = { version = "=0.8.0", path = "../core" }
