# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-search-index-tantivy"
description = "aoide - [experimental] Full-text search index based on Tantivy"
publish = false
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.86"
strum = "0.26.3"
log = "0.4.22"
tantivy = "0.22.0"
thiserror = "1.0.63"

# Workspace dependencies
aoide-core.workspace = true
