# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-search-index-tantivy"
description = "aoide - [experimental] Full-text search index based on Tantivy"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.69"
num-traits = "0.2.15"
log = "0.4.17"
tantivy = "0.19.2"
thiserror = "1.0.38"

# Workspace dependencies
aoide-core = "=0.8.0"
