[alias]
clippy-lints = "clippy --all-targets --no-deps -- --cap-lints warn"

[build]
# https://github.com/rust-lang/rust-analyzer/issues/5828#issuecomment-1120283599
#rustflags = [
#    "-W", "missing-debug-implementations",
#    "-W", "rust-2018-idioms",
#    "-W", "rust-2021-compatibility",
#    "-W", "unreachable-pub",
#    "-W", "unsafe-code",
#    "-W", "clippy::all",
#    "-W", "clippy::explicit-deref-methods",
#    "-W", "clippy::explicit-into-iter-loop",
#    "-W", "clippy::explicit-iter-loop",
#    "-W", "clippy::must-use-candidate",
#]
#rustdocflags = [
#    "-W", "broken-intra-doc-links",
#]
