# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-backend-webapi-json"
description = "aoide - Asynchronous API for a standalone web server (JSON/HTTP)"
version.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = "1.0.65"
diesel = { version = "2.0.0", default-features = false, features = ["sqlite"] }
log = "0.4.17"
serde = { version = "1.0.145" }
thiserror = "1.0.37"
url = "2.3.1"

# tracing
tracing = { version = "0.1.36", features = ["log"] }
uuid = { version = "1.1.2", features = ["v4"] }

# JSON Schema (optional)
schemars = { version = "0.8.10", optional = true }

# Workspace dependencies
aoide-core = { version = "=0.8.0", features = ["serde"] }
aoide-core-api = "=0.8.0"
aoide-core-json = "=0.8.0"
aoide-core-api-json = { version = "=0.8.0", features = ["backend"] }
aoide-media = "=0.8.0"
aoide-repo = "=0.8.0"
aoide-repo-sqlite = "=0.8.0"
aoide-usecases = "=0.8.0"
aoide-usecases-sqlite = "=0.8.0"

[features]
default = []
json-schema = [
    "schemars",
    "aoide-core/json-schema",
    "aoide-core-api-json/json-schema",
    "aoide-core-json/json-schema",
]
