[package]
name = "aoide-backend-webapi-json"
description = "aoide - Asynchronous API for a standalone web server (JSON/HTTP)"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.58"
diesel = { version = "1.4.8", default-features = false, features = ["sqlite"] }
log = "0.4.17"
serde = { version = "1.0.138", default-features = false }
thiserror = "1.0.31"
url = "2.2.2"

# tracing
tracing = { version = "0.1.35", features = ["log"] }
uuid = { version = "1.1.2", features = ["v4"] }

# JSON Schema (optional)
schemars = { version = "0.8.10", optional = true }

# Workspace dependencies
aoide-core = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-core-json = "=0.8.0"
aoide-core-api-json = { version = "=0.8.0", features = ["backend"] }
aoide-media = "=0.8.0"
aoide-repo = "=0.8.0"
aoide-usecases = "=0.8.0"
aoide-usecases-sqlite = "=0.8.0"

[features]
default = []
schemars = [
    "dep:schemars",
    "aoide-core-api-json/schemars",
    "aoide-core-json/schemars",
]
