# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core"
description = "aoide - Core domain model"
repository = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = "1.0.79"
aho-corasick = "1.1.2"
bitflags = "2.4.2"
data-encoding = "2.5.0"
derive_more = "0.99.17"
image = { version = "0.24.8", default-features = false, features = ["png"] }
mime = "0.3.17"
nonicle = "0.1.0"
rand = "0.8.5"
regex = "1.10.3"
semval = "0.5.1"
strum = { version = "0.25.0", features = ["derive"] }
time = { version = "0.3.31", features = [
    "macros",
    "local-offset",
    "parsing",
    "formatting",
] }
thiserror = "1.0.56"
ulid = "1.1.0"
url = "2.5.0"

# Serialization of selected, primitive types
serde = { version = "1.0.195", optional = true, features = ["derive"] }

# JSON Schema (optional)
schemars = { version = "0.8.16", optional = true, features = ["url"] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = "0.2.12"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
path-slash = "0.2.1"

[dev-dependencies]
data-url = "0.3.1"

[features]
default = []
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["getrandom/js", "time/wasm-bindgen"]
serde = ["dep:serde", "ulid/serde", "url/serde"]
json-schema = ["serde", "dep:schemars"]
