[package]
name = "aoide-core"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.56"
bs58 = "0.4.0"
bitflags = "1.3.2"
mime = "0.3.16"
num-derive = "0.3.3"
num-traits = "0.2.14"
once_cell = "1.10.0"
path-slash = "0.1.4"
rand = "0.8.5"
semval = "0.3.0"
time = { version = "0.3.9", features = ["macros", "local-offset", "parsing", "formatting"] }
thiserror = "1.0.30"
url = "2.2.2"

# Dirty hack to support wasm32-unknown-unknown target. Otherwise
# compilation will fail for this transitive dependency needed
# by uuid and rand_core.
# TODO: Remove if no longer needed
getrandom = { version = "0.2.6", default-features = false, features = ["js"] }

[features]
default = []
std-file = []
std-system-time = []

[dev-dependencies]
criterion = "0.3.5"
uuid = { version = "0.8.2", features = ["v4"] }

[[bench]]
name = "entity_uid_benchmark"
harness = false
