[package]
name = "aoide-core"
description = "aoide - Core domain model"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bs58 = "0.4.0"
bitflags = "1.3.2"
mime = "0.3.16"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.12.0"
semval = "0.3.0"
time = { version = "0.3.9", features = [
    "macros",
    "local-offset",
    "parsing",
    "formatting",
] }
thiserror = "1.0.31"
url = "2.2.2"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
path-slash = "0.1.4"
rand = "0.8.5"

[features]
default = []
