[package]
name = "aoide-core"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1"
bs58 = "0.4"
bitflags = "1.3"
mime = "0.3"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1.9"
rand = "0.8"
semval = "0.2"
time = {version = "0.3.7", features = ["macros", "local-offset", "parsing", "formatting"] }
thiserror = "1"
url = "2.2"

# Dirty hack to support wasm32-unknown-unknown target. Otherwise
# compilation will fail for this transitive dependency needed
# by uuid and rand_core.
# TODO: Remove if no longer needed
getrandom = { version = "*", default-features = false, features = ["js"] }

[features]
default = ["with-std-file", "with-std-system-time"]
with-std-file = []
with-std-system-time = []

[dev-dependencies]
criterion = "0.3"
uuid = { version = "0.8", features = ["v4"] }

[[bench]]
name = "entity_uid_benchmark"
harness = false
