# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core"
description = "aoide - Core domain model"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
bs58 = "0.4"
bitflags = "1.3"
mime = "0.3"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1.13"
rand = "0.8"
semval = "0.4"
time = { version = "0.3", features = [
    "macros",
    "local-offset",
    "parsing",
    "formatting",
] }
thiserror = "1.0"
url = "2.2"

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = "0.2"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
path-slash = "0.2"

[features]
default = []
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["getrandom/js"]
