# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core"
description = "aoide - Core domain model"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.68"
bitflags = "1.3.2"
mime = "0.3.16"
nonicle = "0.1.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
rand = "0.8.5"
semval = "0.5.0"
time = { version = "0.3.17", features = [
    "macros",
    "local-offset",
    "parsing",
    "formatting",
] }
thiserror = "1.0.38"
ulid = "1.0.0"
url = "2.3.1"

# Serialization of selected, primitive types
serde = { version = "1.0.152", optional = true, features = ["derive"] }

# JSON Schema (optional)
schemars = { version = "0.8.11", optional = true, features = ["url"] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = "0.2.8"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
path-slash = "0.2.1"

[features]
default = []
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["getrandom/js", "time/wasm-bindgen"]
serde = ["dep:serde", "ulid/serde", "url/serde"]
json-schema = ["serde", "schemars"]
