# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core"
description = "aoide - Core domain model"
publish = false
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.86"
aho-corasick = "1.1.3"
bitflags = "2.6.0"
data-encoding = "2.6.0"
derive_more = { version = "1.0.0", features = ["display", "error"] }
image = { version = "0.25.2", default-features = false, features = ["png"] }
jiff = "0.1.11"
mime = "0.3.17"
nonicle = "0.1.1"
num-integer = "0.1.46"
rand = "0.8.5"
regex = "1.10.6"
semval = "0.5.2"
strum = { version = "0.26.3", features = ["derive"] }
time = { version = "0.3.36", features = [
    "macros",
    "parsing",
    "formatting",
] }
ulid = "1.1.3"
url = "2.5.2"

# Serialization of selected, primitive types
serde = { version = "1.0.209", optional = true, features = ["derive"] }

# JSON Schema (optional)
schemars = { version = "0.8.21", optional = true, features = ["url"] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = "0.2.15"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
path-slash = "0.2.1"

[dev-dependencies]
data-url = "0.3.1"
serde_json = "1.0.127"

[features]
default = []
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["getrandom/js", "jiff/js", "time/wasm-bindgen"]
serde = ["dep:serde", "time/serde-human-readable", "ulid/serde", "url/serde"]
json-schema = ["serde", "dep:schemars"]
