# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core"
description = "aoide - Core domain model"
version.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = "1.0.65"
bitflags = "1.3.2"
mime = "0.3.16"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.15.0"
rand = "0.8.5"
semval = "0.4.0"
time = { version = "0.3.14", features = [
    "macros",
    "local-offset",
    "parsing",
    "formatting",
] }
thiserror = "1.0.36"
ulid = "1.0.0"
url = "2.3.1"

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = "0.2.7"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
path-slash = "0.2.1"

# Serialization of selected, primitive types
serde = { version = "1.0.145", optional = true, features = ["derive"] }

# JSON Schema (optional)
schemars = { version = "0.8.10", optional = true, features = ["url"] }

[features]
default = []
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["getrandom/js"]
serde = ["dep:serde", "ulid/serde", "url/serde"]
json-schema = ["serde", "schemars"]
