# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core"
description = "aoide - Core domain model"
publish = false
version = "0.0.0"
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = "1.0.86"
aho-corasick = "1.1.3"
bitflags = "2.5.0"
data-encoding = "2.6.0"
derive_more = "0.99.17"
image = { version = "0.25.1", default-features = false, features = ["png"] }
mime = "0.3.17"
nonicle = "0.1.1"
rand = "0.8.5"
regex = "1.10.4"
semval = "0.5.2"
strum = { version = "0.26.2", features = ["derive"] }
time = { version = "0.3.36", features = [
    "macros",
    "local-offset",
    "parsing",
    "formatting",
] }
thiserror = "1.0.61"
ulid = "1.1.2"
url = "2.5.0"

# Serialization of selected, primitive types
serde = { version = "1.0.202", optional = true, features = ["derive"] }

# JSON Schema (optional)
schemars = { version = "0.8.20", optional = true, features = ["url"] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = "0.2.15"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
path-slash = "0.2.1"

[dev-dependencies]
data-url = "0.3.1"
serde_json = "1.0.117"

[features]
default = []
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["getrandom/js", "time/wasm-bindgen"]
serde = ["dep:serde", "time/serde-human-readable", "ulid/serde", "url/serde"]
json-schema = ["serde", "dep:schemars"]
