[package]
name = "aoide-core"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "*"
bs58 = "^0.4"
bitflags = "*"
chrono = { version = "*", default-features = false, features = ["clock"] }
mime = "*"
num-derive = "*"
num-traits = "*"
once_cell = "*"
rand = "*"
semval = "*"
thiserror = "*"
url = "*"

# Dirty hack to support wasm32-unknown-unknown target. Otherwise
# compilation will fail for this transitive dependency needed
# by uuid and rand_core.
# TODO: Remove if no longer needed
getrandom = { version = "*", default-features = false, features = ["js"] }

[features]
default = []

[dev-dependencies]
criterion = "*"
uuid = { version = "*", features = ["v4"] }

[[bench]]
name = "entity_uid_benchmark"
harness = false
