[package]
name = "aoide-core"
version = "0.0.1"
authors = [ "Uwe Klotz <uwe.klotz@gmail>" ]
description = "Backend services for curating and enjoying your music"
publish = false

[dependencies]
base64 = { version = "*" }
chrono = { version = "*", features = ["serde"] }
failure = "*"
log = "*"
mime = "*"
ring = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
uuid = { version = "*", features = ["serde", "v1", "v4"] }

[dev-dependencies]
mime_guess = "*"