[package]
name = "aoide-usecases-sqlite"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
diesel = { version = "1.4.8", default-features = false, features = ["sqlite"] }
diesel_migrations =  { version = "1.4.0", default-features = false, features = ["sqlite"] }
log = "0.4.16"
semval = "0.3.0"
thiserror = "1.0.31"

tokio = { version = "1.18.0", optional = true, default-features = false }

# Workspace dependencies
aoide-core = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-media = "=0.8.0"
aoide-repo = "=0.8.0"
aoide-repo-sqlite = "=0.8.0"
aoide-storage-sqlite = "=0.8.0"
aoide-usecases = "=0.8.0"

[features]
default = []
tokio = ["dep:tokio", "aoide-storage-sqlite/tokio"]
