[package]
name = "aoide-usecases-sqlite"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "*"
diesel = { version = "*", default-features = false, features = ["r2d2", "sqlite"] }
diesel_migrations =  { version = "*", default-features = false, features = ["sqlite"] }
r2d2 = "*"
semval = "*"
thiserror = "*"
tracing = { version = "*", features = ["log"] }

# Workspace dependencies
aoide-core = "*"
aoide-core-ext = "*"
aoide-media = "*"
aoide-repo = "*"
aoide-repo-sqlite = "*"
aoide-usecases = "*"

[features]
default = []
