# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-usecases-sqlite"
description = "aoide - SQLite wrappers for aoide-usecases"
publish = false
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
diesel.workspace = true
log.workspace = true
thiserror.workspace = true
url.workspace = true

# Workspace dependencies
aoide-core.workspace = true
aoide-core-api.workspace = true
aoide-media-file.workspace = true
aoide-repo.workspace = true
aoide-repo-sqlite.workspace = true
aoide-storage-sqlite.workspace = true
aoide-usecases = { "workspace" = true, features = ["media-file"] }

[features]
default = []
