[package]
name = "aoide-usecases-sqlite"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1"
diesel = { version = "1.4.8", default-features = false, features = ["sqlite"] }
diesel_migrations =  { version = "1.4", default-features = false, features = ["sqlite"] }
log = "0.4"
semval = "0.2"
thiserror = "1"

tokio = { version = "1", optional = true, default-features = false }

# Workspace dependencies
aoide-core = "*"
aoide-core-api = "*"
aoide-media = "*"
aoide-repo = "*"
aoide-repo-sqlite = "*"
aoide-storage-sqlite = "*"
aoide-usecases = "*"

[features]
default = []
with-tokio = ["tokio", "aoide-storage-sqlite/with-tokio"]
