# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-usecases-sqlite"
description = "aoide - SQLite wrappers for aoide-usecases"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
publish = false

[dependencies]
anyhow = "1.0.70"
diesel = { version = "2.0.4", default-features = false, features = ["sqlite"] }
log = "0.4.17"
thiserror = "1.0.40"

# Workspace dependencies
aoide-core = "=0.8.0"
aoide-core-api = "=0.8.0"
aoide-media = "=0.8.0"
aoide-repo = "=0.8.0"
aoide-repo-sqlite = "=0.8.0"
aoide-storage-sqlite = "=0.8.0"
aoide-usecases = { version = "=0.8.0", features = ["media"] }

[features]
default = []
