# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-usecases-sqlite"
description = "aoide - SQLite wrappers for aoide-usecases"
publish = false
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.86"
diesel = { version = "2.2.1", default-features = false, features = ["sqlite"] }
log = "0.4.22"
thiserror = "1.0.62"
url = "2.5.2"

# Workspace dependencies
aoide-core.workspace = true
aoide-core-api.workspace = true
aoide-media-file.workspace = true
aoide-repo.workspace = true
aoide-repo-sqlite.workspace = true
aoide-storage-sqlite.workspace = true
aoide-usecases = { "workspace" = true, features = ["media-file"] }

[features]
default = []
