[package]
name = "aoide-usecases-sqlite"
version = "0.0.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "*"
diesel = { version = "*", default-features = false, features = ["sqlite"] }
diesel_migrations =  { version = "*", default-features = false, features = ["sqlite"] }
log = "*"
semval = "*"
thiserror = "*"

tokio = { version = "*", optional = true, default-features = false }

# Workspace dependencies
aoide-core = "*"
aoide-core-api = "*"
aoide-media = "*"
aoide-repo = "*"
aoide-repo-sqlite = "*"
aoide-storage-sqlite = "*"
aoide-usecases = "*"

[features]
default = []
with-tokio = ["tokio", "aoide-storage-sqlite/with-tokio"]
