# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-usecases-sqlite"
description = "aoide - SQLite wrappers for aoide-usecases"
repository = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = "1.0.71"
diesel = { version = "2.1.0", default-features = false, features = ["sqlite"] }
log = "0.4.17"
thiserror = "1.0.40"

# Workspace dependencies
aoide-core = { version = "=0.8.0", path = "../core" }
aoide-core-api = { version = "=0.8.0", path = "../core-api" }
aoide-media-file = { version = "=0.8.0", path = "../media-file" }
aoide-repo = { version = "=0.8.0", path = "../repo" }
aoide-repo-sqlite = { version = "=0.8.0", path = "../repo-sqlite" }
aoide-storage-sqlite = { version = "=0.8.0", path = "../storage-sqlite" }
aoide-usecases = { version = "=0.8.0", path = "../usecases", features = ["media-file"] }

[features]
default = []
