# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-websrv-warp-sqlite"
description = "aoide - Routes and handlers for a web server (warp/SQLite)"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.58"
log = "0.4.17"
serde = "1.0.139"
thiserror = "1.0.31"
tokio = "1.20.0"
warp = { version = "0.3.2", default-features = false }

# Workspace dependencies
aoide-backend-webapi-json = "=0.8.0"
aoide-repo = "=0.8.0"
aoide-storage-sqlite = "=0.8.0"
aoide-usecases-sqlite = { version = "=0.8.0", features = ["tokio"] }
