# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-websrv-warp-sqlite"
description = "aoide - Routes and handlers for a web server (warp/SQLite)"
repository = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1.0.78"
log = "0.4.20"
serde = "1.0.193"
thiserror = "1.0.53"
warp = { version = "0.3.6", default-features = false }

# Workspace dependencies
aoide-backend-webapi-json = { path = "../backend-webapi-json" }
aoide-repo = { path = "../repo" }
aoide-storage-sqlite = { path = "../storage-sqlite" }
aoide-usecases-sqlite = { path = "../usecases-sqlite" }
