[package]
name = "aoide-core-serde"
version = "0.3.3"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
publish = false
edition = "2018"

[dependencies]
aoide-core = "*"
chrono = { version = "*", default-features = false, features = ["serde"] }
semval = "*"
serde = { version = "*", features = ["derive"] }
serde_repr = "*"

[dev-dependencies]
serde_json = "*"
