[package]
name = "aoide-webapp"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "*"
hyper = { version = "*", default-features = false }
seed = "*"
serde = { version = "*", features = ["derive"] }
serde_urlencoded = "*"
thiserror = "*"
url = "*"

# Workspace dependencies
aoide-core = { version = "*", default-features = false }
aoide-core-api = "*"
aoide-core-json = "*"
aoide-core-api-json = { version = "*", features = ["frontend"] }

[patch.crates-io]
aoide-core = { path = "../crates/core" }
aoide-core-json = { path = "../crates/core-json" }
aoide-core-api = { path = "../crates/core-api" }
aoide-core-api-json = { path = "../crates/core-api-json" }
