[package]
name = "aoide-webapp"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "*"
hyper = { version = "*", default-features = false }
seed = "*"
serde = { version = "*", features = ["derive"] }
thiserror = "*"
url = "*"

# Workspace dependencies
aoide-core = "*"
aoide-core-ext = "*"
aoide-core-serde = "*"
aoide-core-ext-serde = { version = "*", features = ["frontend"] }

[patch.crates-io]
aoide-core = { path = "../crates/core" }
aoide-core-serde = { path = "../crates/core-serde" }
aoide-core-ext = { path = "../crates/core-ext" }
aoide-core-ext-serde = { path = "../crates/core-ext-serde" }
