# SPDX-FileCopyrightText: Copyright (C) 2018-2025 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

# Same as file name
name: audit-dependencies

permissions:
  contents: read

on:
  push:
    paths:
      - "**/Cargo.toml"
  schedule:
    # Weekly, i.e. on Sunday at 13:37 UTC
    - cron: "37 13 * * 0"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          # Keep in sync with `Cargo.toml`.
          rust-version: "1.91"
          command: check
          arguments: >-
            --all-features
            --locked
