# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - dev

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short

jobs:
  continuous-integration:
    name: Building project and running tests
    runs-on: ubuntu-latest

    steps:
      - name: Install extra dependencies for egui on Linux
        run: |
          sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install Rust toolchain for webapp
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: stable
          profile: minimal

      - name: Install Trunk for building the webapp
        run: |
          cargo install --locked trunk

      # Cache key depends on Rust toolchain!
      - name: "Cache build artifacts"
        uses: Swatinem/rust-cache@v1

      - name: Check aoide-core
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/core/Cargo.toml

      - name: Check aoide-core-json
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/core-json/Cargo.toml

      - name: Check aoide-core-api
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/core-api/Cargo.toml

      - name: Check aoide-core-api-json
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/core-api-json/Cargo.toml

      - name: Check aoide-media
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/media/Cargo.toml

      - name: Check aoide-repo
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/repo/Cargo.toml

      - name: Check aoide-repo-sqlite
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/repo-sqlite/Cargo.toml

      - name: Check aoide-storage-sqlite
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/storage-sqlite/Cargo.toml

      - name: Check aoide-search-index-tantivy
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/search-index-tantivy/Cargo.toml

      - name: Check aoide-usecases
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/usecases/Cargo.toml

      - name: Check aoide-usecases-sqlite
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/usecases-sqlite/Cargo.toml

      - name: Check aoide-backend-embedded
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/backend-embedded/Cargo.toml

      - name: Check aoide-backend-webapi-json
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/backend-webapi-json/Cargo.toml

      - name: Check aoide-websrv-warp-sqlite
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/websrv-warp-sqlite/Cargo.toml

      - name: Build aoide-webapp artifacts
        run: |
          cd webapp
          trunk build
          cd -

      - name: Check aoide-websrv
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path websrv/Cargo.toml

      - name: Check aoide-client
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path crates/client/Cargo.toml

      - name: Check aoide-webcli
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-features --all-targets --manifest-path webcli/Cargo.toml

      - name: Build tests with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --all-features --all-targets --workspace --no-run

      - name: Run tests with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --all-features --all-targets --workspace -- --nocapture --quiet

      - name: Build release with default features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --workspace --all-targets --profile release
