name: Continuous integration

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - development

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Install system dependencies
#        run: |
#          sudo apt-get install libsqlite3-dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Check aoide-core crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path core/Cargo.toml

      - name: Check aoide-core-serde crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path core-serde/Cargo.toml

      - name: Check aoide-repo crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path repo/Cargo.toml

      - name: Check aoide-repo-sqlite crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path repo-sqlite/Cargo.toml

      - name: Test project
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check for linter warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
