name: Continuous integration

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - development

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
          target: x86_64-unknown-linux-musl

      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check for linter warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Check sub-crate core
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path core/Cargo.toml

      - name: Check sub-crate core-serde
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path core-serde/Cargo.toml

      - name: Check sub-crate repo
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path repo/Cargo.toml

      - name: Check sub-crate repo-sqlite
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path repo-sqlite/Cargo.toml

      - name: Test project
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
