# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: pre-release

on:
  push:
    tags:
      - 'v[0-9]+*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload-artifacts:
    name: Building and uploading artifacts
    runs-on: ${{ matrix.runner_os }}
    strategy:
      matrix:
        build_profile:
          - production
        target:
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-musl
            runner_os: ubuntu-latest
            artifact_suffix: .tar.xz
          - target: x86_64-apple-darwin
            runner_os: macos-latest
            artifact_suffix: .tar.xz
          - target: x86_64-pc-windows-msvc
            runner_os: windows-latest
            artifact_suffix: .7z

    steps:
      - name: Install dependencies for `musl libc`
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt -y install musl-tools

      - name: 'Install dependencies for `egui`'
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Rust toolchain for webapp
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Trunk for building the webapp
        run: |
          cargo install --locked trunk

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v1

      - name: Build artifact
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --target ${{ matrix.target }} --profile ${{ matrix.build_profile }}

      - name: Prepare artifact on Linux/macOS
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          cd target/${{ matrix.target }}/${{ matrix.build_profile }}
          tar cJvf ../../../aoide-${{ matrix.target }}${{ matrix.artifact_suffix }} aoide
          cd -
      - name: Prepare artifact on Windows
        if: runner.os == 'Windows'
        run: |
          cd target/${{ matrix.target }}/${{ matrix.build_profile }}
          7z a ../../../aoide-${{ matrix.target }}${{ matrix.artifact_suffix }} aoide.exe
          cd -

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: aoide-${{ matrix.target }}${{ matrix.artifact_suffix }}
          path: aoide-${{ matrix.target }}${{ matrix.artifact_suffix }}

  create-release-draft:
    name: Creating release draft
    needs: build-and-upload-artifacts
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Generate artifact checksums
        run: for file in aoide-*/aoide-*; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done

      - name: Extract release notes from changelog
        run: cat CHANGELOG.md | tail -n +7 | head -n 25 > RELEASE_NOTES.md

      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          files: aoide-*/aoide-*
          body_path: RELEASE_NOTES.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
