[package]
name = "aoide-repo-sqlite"
version = "0.0.0"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
publish = false
edition = "2018"

[dependencies]
aoide-core = "*"
aoide-repo = "*"
anyhow = "*"
log = "*"
num-derive = "*"
num-traits = "*"
semval = "*"
diesel = { version = "*", features = ["sqlite", "64-column-tables", "numeric", "chrono"] }
# TODO: Unpin num-bigint after Diesel update!
libsqlite3-sys = { version = "0.9", features = ["bundled"] }
bigdecimal = "0.1"
num-bigint = "0.2"

[features]
default = []

[dev-dependencies]
diesel_migrations =  { version = "*", features = ["sqlite"] }
