[package]
name = "aoide-repo-sqlite"
version = "0.0.0"
authors = [ "Uwe Klotz <uwe.klotz@gmail>", "et al." ]
license = "AGPL-3.0-or-later"
publish = false
edition = "2018"

[dependencies]
aoide-core = "*"
aoide-repo = "*"
bigdecimal = "*"
chrono = { version = "*", default-features = false }
diesel = { version = "*", features = ["chrono", "sqlite", "numeric"] }
anyhow = "*"
log = "*"
# TODO: Unpin num-bigint after Diesel update!
num-bigint = { version = "0.2" }
num-traits = "*"
percent-encoding = "*"

[dev-dependencies]
diesel_migrations =  { version = "*", features = ["sqlite"] }
