# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core-json"
description = "aoide - JSON mapping for aoide-core boundary types"
version.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = "1.0.65"
base64 = "0.13.0"
mime = "0.3.16"
num-traits = "0.2.15"
semval = "0.4.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_repr = "0.1.9"
time = { version = "0.3.15", features = ["serde-well-known"] }
url = { version = "2.3.1", features = ["serde"] }

# JSON Schema (optional)
schemars = { version = "0.8.11", optional = true, features = ["chrono", "url"] }
chrono = { version = "0.4.22", optional = true, default-features = false }

# Workspace dependencies
aoide-core = { version = "=0.8.0", features = ["serde"] }

[features]
default = []
json-schema = ["schemars", "chrono", "aoide-core/json-schema"]
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["aoide-core/js"]

[dev-dependencies]
serde_json = "1.0.86"
