[package]
name = "aoide-core-json"
description = "aoide - JSON mapping for aoide-core boundary types"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
mime = "0.3.16"
num-traits = "0.2.15"
semval = "0.3.0"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
serde_repr = "0.1.8"
time = { version = "0.3.9", features = ["serde-well-known"] }
url = { version = "2.2.2", features = ["serde"] }

# JSON Schema (optional)
schemars = { version = "0.8.10", optional = true, features = ["url"] }

# Workspace dependencies
aoide-core = "=0.8.0"

[features]
default = []
schemars = ["dep:schemars"]

[dev-dependencies]
serde_json = "1.0.81"
