# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core-json"
description = "aoide - JSON mapping for aoide-core boundary types"
repository = { workspace = true }
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = "1.0.75"
data-encoding = "2.4.0"
mime = "0.3.17"
serde = { version = "1.0.193", features = ["derive"] }
serde_repr = "0.1.17"
time = { version = "0.3.30", features = ["serde-human-readable"] }
url = { version = "2.4.1", features = ["serde"] }

# JSON Schema (optional)
schemars = { version = "0.8.16", optional = true, features = ["chrono", "url"] }
chrono = { version = "0.4.31", optional = true, default-features = false }

# Workspace dependencies
aoide-core = { version = "=0.8.0", path = "../core", features = ["serde"] }

[features]
default = []
json-schema = ["dep:schemars", "dep:chrono", "aoide-core/json-schema"]
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["aoide-core/js"]

[dev-dependencies]
serde_json = "1.0.108"
