# SPDX-FileCopyrightText: Copyright (C) 2018-2022 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core-json"
description = "aoide - JSON mapping for aoide-core boundary types"
version = "0.8.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
mime = "0.3"
num-traits = "0.2"
semval = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
time = { version = "0.3", features = ["serde-well-known"] }
url = { version = "2.2", features = ["serde"] }

# JSON Schema (optional)
schemars = { version = "0.8", optional = true, features = ["chrono", "url"] }
chrono = { version = "0.4", optional = true, default-features = false }

# Workspace dependencies
aoide-core = { version = "=0.8.0", features = ["serde"] }

[features]
default = []
json-schema = ["schemars", "chrono", "aoide-core/json-schema"]
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["aoide-core/js"]

[dev-dependencies]
serde_json = "1.0"
