# SPDX-FileCopyrightText: Copyright (C) 2018-2023 Uwe Klotz <uwedotklotzatgmaildotcom> et al.
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "aoide-core-json"
description = "aoide - JSON mapping for aoide-core boundary types"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.68"
base64 = "0.21.0"
mime = "0.3.16"
nonicle = "0.0.1"
num-traits = "0.2.15"
semval = "0.5.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_repr = "0.1.10"
time = { version = "0.3.17", features = ["serde-human-readable"] }
url = { version = "2.3.1", features = ["serde"] }

# JSON Schema (optional)
schemars = { version = "0.8.11", optional = true, features = ["chrono", "url"] }
chrono = { version = "0.4.23", optional = true, default-features = false }

# Workspace dependencies
aoide-core = { version = "=0.8.0", features = ["serde"] }

[features]
default = []
json-schema = ["schemars", "chrono", "aoide-core/json-schema"]
# Feature to enable JavaScript bindings on wasm32-unknown-unknown
js = ["aoide-core/js"]

[dev-dependencies]
serde_json = "1.0.91"
